# -*- coding: utf-8 -*-
"""
HeadlessPlayer NVDA Add-on - Online Streaming Engine Module.
Aggregates models, resolver, search explorer, and updater submodules into a unified interface.
"""

from __future__ import annotations

from .models import (
    StreamItem,
    ITEM_VIDEO,
    ITEM_SHORTS,
    ITEM_PLAYLIST,
    ITEM_CHANNEL,
    ITEM_LISTING,
    normalize_url,
    extract_url,
    is_url,
    is_youtube_url,
    classify_flat_entry,
    _SilentLogger,
)
from .updater import (
    LIB_DIR,
    _get_ytdlp,
    reset_ytdlp_state,
    is_available,
    get_unavailable_reason,
    get_installed_version,
    get_bundled_version,
    YTDLP_CHANNELS,
    BUNDLED_BACKUP_DIR,
    PREVIOUS_BACKUP_DIR,
    META_FILE,
    ensure_bundled_snapshot,
    can_rollback,
    can_reset_bundled,
    get_channel_info,
    check_latest_version,
    update_ytdlp,
    rollback_ytdlp,
    reset_to_bundled_ytdlp,
)
from .resolver import (
    SUPPORTED_COOKIE_BROWSERS,
    _resolve_cache,
    _resolve_cache_lock,
    _RESOLVE_CACHE_TTL,
    get_manual_cookies_file,
    login_cookies_enabled,
    is_bot_error,
    is_cookie_error,
    check_youtube_cookies_validity,
    resolve_stream,
    clear_resolve_cache,
    _base_ydl_opts,
)
from .search import (
    get_account_sections,
    _prepare_listing_url,
    search_youtube,
    fetch_listing,
    probe_url,
    clear_listing_cache,
)

__all__ = [
    "LIB_DIR",
    "StreamItem",
    "ITEM_VIDEO",
    "ITEM_SHORTS",
    "ITEM_PLAYLIST",
    "ITEM_CHANNEL",
    "ITEM_LISTING",
    "normalize_url",
    "extract_url",
    "is_url",
    "is_youtube_url",
    "classify_flat_entry",
    "_SilentLogger",
    "_get_ytdlp",
    "reset_ytdlp_state",
    "is_available",
    "get_unavailable_reason",
    "get_installed_version",
    "get_bundled_version",
    "YTDLP_CHANNELS",
    "BUNDLED_BACKUP_DIR",
    "PREVIOUS_BACKUP_DIR",
    "META_FILE",
    "ensure_bundled_snapshot",
    "can_rollback",
    "can_reset_bundled",
    "get_channel_info",
    "check_latest_version",
    "update_ytdlp",
    "rollback_ytdlp",
    "reset_to_bundled_ytdlp",
    "SUPPORTED_COOKIE_BROWSERS",
    "_resolve_cache",
    "_resolve_cache_lock",
    "_RESOLVE_CACHE_TTL",
    "get_manual_cookies_file",
    "login_cookies_enabled",
    "is_bot_error",
    "is_cookie_error",
    "check_youtube_cookies_validity",
    "resolve_stream",
    "clear_resolve_cache",
    "_base_ydl_opts",
    "get_account_sections",
    "_prepare_listing_url",
    "search_youtube",
    "fetch_listing",
    "probe_url",
]
